[package]
name = "receive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smtp = {path = "../smtp"}

native-tls = "0.2"
trust-dns-resolver = "0.21"
chrono = "0.4"